name: flu_cli

environment:
  sdk: ">=3.8.1 <4.0.0"

dev_dependencies:
  melos: ^7.0.0-dev.9
  path: ^1.9.1
  very_good_analysis: ^9.0.0
  yaml: ^3.1.3

workspace:
  - packages/flu

melos:
  repository: https://github.com/albinpk/flu_cli
  command:
    version:
      hooks:
        preCommit: |
          dart run scripts/generate_version.dart && \
          git add packages/flu/lib/src/version.g.dart
        post: dart pub publish --dry-run --directory=packages/flu
