name: flu
description: >
  A powerful Flutter CLI tool to scaffold, configure, and bootstrap projects 
  with FVM, Melos, state management, navigation, model generators, and more.

version: 0.0.1-dev.2

homepage: https://github.com/albinpk/flu_cli
repository: https://github.com/albinpk/flu_cli
issue_tracker: https://github.com/albinpk/flu_cli/issues

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  change_case: ^2.2.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  path: ^1.9.1
  process_run: ^1.2.4
  watcher: ^1.1.2
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  test: ^1.26.2

executables:
  flu:

topics:
  - flutter
  - cli
  - project-generator
  - automation
  - melos
