name: flu
description: Flutter Utility for Developers
version: 0.0.1-dev.1

resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
